spring.application.name=ExpenseAppV2

#Database connection
spring.datasource.url=jdbc:h2:mem:expenseDb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/my-h2-console
spring.jpa.show-sql=true
